// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/02/2026, 13:39:27
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/cliz/roundabout/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/plugins/**/*.{js,ts,mjs}","C:/Users/cliz/roundabout/composables/**/*.{js,ts,mjs}","C:/Users/cliz/roundabout/utils/**/*.{js,ts,mjs}","C:/Users/cliz/roundabout/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/cliz/roundabout/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;